version: "3.7"

networks:
    website:

services:
    website-db:
        image: mysql:5.6.34
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - "website-db:/var/lib/mysql"
            - './docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
        networks:
            - website

    website-backend:
        build:
            context: ../..
            dockerfile: docker/development/Dockerfile
        volumes:
            - "../..:/app"
            - "website-node_modules:/app/node_modules"
        ports:
            - "8000:8000"
        networks:
            - website
        depends_on:
            - website-db
        command: "/app/tools/development.sh"

volumes:
    website-db:
    website-node_modules:
