# Generated by Django 3.0.8 on 2020-07-14 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200714_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-date',), 'verbose_name_plural': 'news'},
        ),
    ]
