# Generated by Django 3.0.8 on 2020-07-12 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social_id',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Kod usunięcia postaci musi zawierać 7 cyfr', regex='^\\d*$')], verbose_name='Kod usunięcia postaci'),
        ),
    ]
