# Generated by Django 3.0.8 on 2020-07-15 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='banlength',
        ),
        migrations.AddField(
            model_name='user',
            name='availDt',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
    ]
