# Generated by Django 3.0.8 on 2020-07-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid1', models.IntegerField(default=0)),
                ('pid2', models.IntegerField(default=0)),
                ('pid3', models.IntegerField(default=0)),
                ('pid4', models.IntegerField(default=0)),
                ('empire', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'player_index',
            },
        ),
        migrations.RenameField(
            model_name='guild',
            old_name='points',
            new_name='ladder_point',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='guild_name',
        ),
        migrations.AddField(
            model_name='guild',
            name='name',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='player',
            name='job',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='playtime',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='kills',
            field=models.IntegerField(db_column='ludzie'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterModelTable(
            name='guild',
            table='guild',
        ),
        migrations.AlterModelTable(
            name='player',
            table='player',
        ),
    ]
