# Generated by Django 3.0.8 on 2020-07-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_auto_20200716_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='draw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guild',
            name='loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guild',
            name='win',
            field=models.IntegerField(default=0),
        ),
    ]
